{
    'name': 'Comunicaciones TYT Contact Center - Soy Calidad',
    'version': '1.0',
    'description': 'Añade características al módulo Comunicaciones TYT Contact Center',
    'summary': 'Añade características al módulo Comunicaciones TYT Contact Center',
    'author': 'Soy Calidad',
    'website': 'www.soycalidad.com',
    'license': '',
    'category': 'soycalidad',
    'depends': [
        'mgmtsystem_comunication',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/comunication_record.xml',
        'views/menus.xml',
        'views/plan.xml',
        'views/comunication_onboarding_templates.xml',
        'views/record_views.xml',
        'report/record_meeting.xml',
    ],
    'auto_install': False,
    'installable': True,
    'application': False,
}
