from . import origin_base
from . import models
from . import comunication
from . import nonconformity
from . import complaint
from . import audit
from . import legal
from . import training
from . import survey
from . import process
from . import opportunity
from . import management_review
from . import maintenance
from . import action
from . import process_integration
from . import employee
from . import target
from . import swot
