{
    'name': 'Contexto TYT Contact Center - Soy Calidad',
    'version': '1.0',
    'description': 'Añade características al módulo Contexto TYT Contact Center',
    'summary': 'Añade características al módulo Contexto TYT Contact Center',
    'author': 'Soy Calidad',
    'website': 'www.soycalidad.com',
    'license': '',
    'category': 'soycalidad',
    'depends': [
        'base',
        'mgmtsystem_context',
        'mgmtsystem_process_integration',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/mail_template_data.xml',
        'views/context.xml',
        'report/stakeholders_report.xml',
        'wizard/product_service_communicate.xml',
        'views/menus.xml',
    ],
    'auto_install': False,
    'installable': True,
    'application': False,
}
