{
    'name': 'Contexto de la organización',
    'version': '1.0',
    'description': 'Añade factores internos y externos además de su analis',
    'summary': 'Añade información acerca del contexto de la organización',
    'author': '',
    'website': '',
    'license': 'LGPL-3',
    'category': '',
    'depends': [
        'mgmtsystem_opportunity',
        'hola_calidad',
        'report_xlsx',
        'mgmtsystem_process',
        'mgmtsystem_validation',
        'hr_organizational_chart',
        'mgmtsystem_documentary_control'
    ],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/stakeholder.stakeholder.csv',
        'views/templates.xml',
        'views/context.xml',
        'wizards/cross_swot_action.xml',
        'views/swot.xml',
        'views/organization_chart.xml',
        'views/pest_analysis.xml',
        'views/context_onboarding_templates.xml',
        'reports/context_policy.xml',
        'reports/context_stakeholder.xml',
        'reports/context_porter_forces.xml',
        'reports/context_swot.xml',
        'reports/context_cross_swot.xml',
        'reports/internal_issue.xml',
        'reports/cover.xml',
        'reports/menus.xml',
        'reports/pest_analysis.xml',
        'wizards/external_issue.xml',
        'wizards/stakeholder.xml',
        'wizards/porter_forces.xml',      
        'wizards/internal_issue.xml',
        'wizards/swot_report.xml',
        'wizards/cross_swot_report.xml',
        'wizards/general_report.xml',
        'wizards/policy.xml',
        'wizards/pestel_report.xml',
        'data/mail_templates.xml',
    ],
    'demo': [
        ''
    ],
    'assets': {
        'web.assets_backend': [
            "/mgmtsystem_context/static/lib/fontawesome/css/font-awesome-extra.css",
            "/mgmtsystem_context/static/src/css/context.css",
        ],
        'web.report_assets_common': [
            "/mgmtsystem_context/static/src/css/report.css",
        ],
    },
    'auto_install': False,
    'application': True,
}
