{
    'name': 'Auditorías TYT Contact Center - Soy Calidad',
    'version': '1.0',
    'description': 'Añade características al módulo Auditorías TYT Contact Center',
    'summary': 'Añade características al módulo Auditorías TYT Contact Center',
    'author': 'Soy Calidad',
    'website': 'www.soycalidad.com',
    'license': '',
    'category': 'soycalidad',
    'depends': [
        'mgmtsystem_validation',
        'mgmtsystem_nonconformity',
        'mgmtsystem_audit',
        'website',
    ],
    'data': [
        'security/ir.model.access.csv',
        'views/audit_plan_tyt_auditor.xml',
        'views/audit_actions.xml',
        'views/audit_application_form.xml',
        'views/audit.xml',
        'views/audit_plan_schedule_line.xml',
        'views/audit_plan_schedule.xml',
        'views/plan.xml',
        'views/audit_report.xml',
        'reports/report_paperformat.xml',
        'reports/report_layout.xml',
        'reports/report_informe.xml',
        'reports/audit_checklist.xml',
        'reports/audit_schedule.xml',
        'data/descriptions.xml',
        'data/activities.xml',
        'data/iso9001_standard.xml',
        'data/iso9001_standard2.xml',
        'data/iso9001_standard3.xml',
        'data/iso9001_standard_complement.xml',
    ],
    'assets': {
        'web.assets_backend': [
            '/tyt_audit/static/src/img/logo_large.png',
            '/tyt_audit/static/src/img/fondo_form.png',
        ],
        'web.assets_frontend': [
            '/tyt_audit/static/src/img/logo_large.png',
            '/tyt_audit/static/src/img/fondo_form.png',
        ],
        'web.report_assets_common': [
            '/tyt_audit/static/src/scss/report_informe.scss',
        ],
    },
    'images': ['/tyt_audit/static/src/img/logo_large.png'],
    'auto_install': False,
    'installable': True,
    'application': False,
}