{
    "name": "Auditorías TYT Contact Center - Soy Calidad",
    "version": "1.0",
    "description": "Añade características al módulo Auditorías TYT Contact Center",
    "summary": "Añade características al módulo Auditorías TYT Contact Center",
    "author": "Soy Calidad",
    "website": "www.soycalidad.com",
    "license": "",
    "category": "soycalidad",
    "depends": [
        "mgmtsystem_validation",
        "mgmtsystem_nonconformity",
        "mgmtsystem_audit",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/audit_plan_tyt_auditor.xml",
        "views/audit_actions.xml",
        "views/audit.xml",
        "views/audit_plan_schedule_line.xml",
        "views/audit_plan_schedule.xml",
        "views/plan.xml",
        "views/audit_report.xml",
        "reports/report_paperformat.xml",
        "reports/report_layout.xml",
        "reports/report_informe.xml",
        "reports/audit_checklist.xml",
        "reports/audit_schedule.xml",
        "data/activities.xml",
        "data/descriptions.xml",
        "data/iso9001_standard.xml",
        "data/iso9001_standard2.xml",
        "data/iso9001_standard3.xml",
    ],
    "assets": {
        "web.report_assets_common": [
            "/tyt_audit/static/src/scss/report_informe.scss",
        ],
    },
    "auto_install": False,
    "installable": True,
    "application": False,
}
