{
    'name': 'Auditorías TYT Contact Center - Soy Calidad',
    'version': '1.0',
    'description': 'Añade características al módulo Auditorías TYT Contact Center',
    'summary': 'Añade características al módulo Auditorías TYT Contact Center',
    'author': 'Soy Calidad',
    'website': 'www.soycalidad.com',
    'license': 'Other proprietary',
    'category': 'soycalidad',
    'depends': [
        'mgmtsystem_validation',
        'mgmtsystem_nonconformity',
        'mgmtsystem_audit',
        'website',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'views/audit_plan_tyt_auditor.xml',
        'views/audit_actions.xml',
        'views/audit_application_form.xml',
        'views/audit.xml',
        'views/audit_plan_schedule_line.xml',
        'views/audit_plan_schedule.xml',
        'views/plan.xml',
        'views/audit_report.xml',
        'views/audit_audit_planning.xml',
        'views/audit_audit_planning_template.xml',
        'views/start_process_audit_audit.xml',
        'reports/report_paperformat.xml',
        'reports/report_layout.xml',
        'reports/report_informe.xml',
        'reports/audit_checklist.xml',
        'reports/audit_schedule.xml',
        'data/descriptions.xml',
        'data/activities.xml',
        'data/iso9001_standard.xml',
        'data/iso9001_standard2.xml',
        'data/iso9001_standard3.xml',
        'data/iso9001_standard_complement.xml',
        'data/mail_template_data.xml',
    ],
    'assets': {
        'web.report_assets_common': [
            '/tyt_audit/static/src/scss/report_informe.scss',
        ],
    },
    'auto_install': False,
    'installable': True,
    'application': False,
}
