{
    'name': 'Integración de Procedimientos',
    'version': '1.0',
    'description': 'Añade procedimientos a la mayoría de modelos del sistema de gestión',
    'summary': 'Añade procedimientos a la mayoría de modelos del sistema de gestión',
    'author': 'Soy Calidad',
    'website': 'www.soycalidad.com',
    'license': 'LGPL-3',
    'category': 'mgmtsystem',
    'depends': [
        'hola_calidad',
        'mgmtsystem_target',
        'mgmtsystem_process',
        'mgmtsystem_infrastructure',
        'mgmtsystem_complaints',
        'mgmtsystem_employees',
        'mgmtsystem_legal',
        'mgmtsystem_nonconformity',
        'mgmtsystem_comunication',
        'mgmtsystem_survey',
        'mgmtsystem_opportunity',
        'mgmtsystem_management_review',
        'mgmtsystem_partner_qualification',
        'purchase',
    ],
    'data': [
        'views/models.xml',
        'security/ir.model.access.csv',
        'views/comunication.xml',
        'views/nonconformity.xml',
        'views/action.xml',
        'views/complaint.xml',
        'views/audit.xml',
        'views/legal.xml',
        'views/context.xml',
        'views/management_review.xml',
        'views/maintenance.xml',
        'views/opportunity.xml',
        'views/process.xml',
        'views/target.xml',
        'views/training.xml',
        'views/survey.xml',
        'views/employee.xml',
        'views/swot.xml',
        'reports/process.xml',
        'wizards/supplier_wizard_views.xml',
        'wizards/process_report.xml',
        'reports/supplier.xml',
        'reports/complaint.xml',
        'reports/recruitment.xml',
        'reports/general_process_report.xml',
    ],
    'demo': [
        ''
    ],
    'auto_install': False,
    'application': False,
}
