{
    'name': 'Documents de Soy Calidad',
    'version': '1.0',
    'description': 'Añade características al módulo Documents(Enterprise)',
    'summary': 'Añade características al módulo Documents(Enterprise)',
    'author': 'Soy Calidad',
    'website': 'www.soycalidad.com',
    'license': '',
    'category': 'soycalidad',
    'depends': [
        #'hola_calidad',
        #'menus_hola_calidad',
        #'calidad_base',
        'documents',
        'mgmtsystem_process_integration',
        'soycalidad_improve',
    ],
    'data': [
        'data/files_data.xml',
        'views/res_config_setting_views.xml',
        'views/communication.xml',
        'views/employees.xml',
        'views/process.xml',
        'views/context.xml',
        'views/opportunity.xml',
        'views/legal.xml',
        'views/survey.xml',
        'views/target.xml',
        'views/maintenance.xml',
        'views/management_review.xml',
        'views/nc.xml',
        'views/action.xml',
        'views/audit.xml',
    ],
    'auto_install': False,
    'installable': True,
    'application': False,
}