{
    'name': 'Reclutamiento TYT Contact Center - Soy Calidad',
    'version': '1.0',
    'description': 'Añade características al módulo Reclutamiento TYT Contact Center',
    'summary': 'Añade características al módulo Reclutamiento TYT Contact Center',
    'author': 'Soy Calidad',
    'website': 'www.soycalidad.com',
    'license': 'Other proprietary',
    'category': 'soycalidad',
    'depends': [
        'hola_calidad',
        'hr_recruitment',
        'report_xlsx',
        'website',
        'survey',
        #'tyt_studio',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/groups.xml',
        'views/view_requisition.xml',
        'data/mail_templates.xml',
        'views/share_templates.xml',
        'reports/reports_xls.xml',
        'reports/reports_pdf.xml',
        'views/template_report_requisition.xml',
        'views/view_job_application.xml',
        'views/job_application_form.xml',
        'views/view_health_survey.xml',
        'views/health_survey_form.xml',
        'views/view_expedient.xml',
        'views/view_attendance_list.xml',
        'views/view_applicant.xml',
        'views/view_survey.xml',
        'wizards/generate_attendance.xml',
        'views/view_evaluation_rubric.xml',
        'data/data_reason_of_withdrawal.xml',
        'data/data_survey_messages.xml',
        'data/evaluation_rubric.xml',
        'wizards/rubric_signature.xml',
        'views/view_certification_feedback.xml',
        'views/certification_feedback_form.xml',
        'views/view_description_letter.xml',
        'views/descriptive_letter_form.xml',
        'views/descriptive_letter_template_form.xml'
    ],
    'auto_install': False,
    'installable': True,
    'application': False,

    'assets': {
        'tyt_recruitment.assets_pdfjs_viewer': [
            # 'tyt_recruitment/static/lib/pdfjs/build/pdf.js',
            # 'tyt_recruitment/static/lib/pdfjs/build/pdf.worker.js',
            # 'tyt_recruitment/static/lib/pdfjs/web/viewer.css',
            # 'tyt_recruitment/static/lib/pdfjs/web/viewer.js',
            # 'tyt_recruitment/static/lib/pdfjs/web/viewer.html',
            'tyt_recruitment/static/lib/pdfjs/web/cmaps/**',
            'tyt_recruitment/static/lib/pdfjs/web/images/**',
            'tyt_recruitment/static/lib/pdfjs/web/locale/**',
        ],
    },
    'images': ["static/src/img/logo.png"],
}