{
    'name': 'DMS de Soy Calidad',
    'version': '1.0',
    'description': 'Añade características al módulo DMS',
    'summary': 'Añade características al módulo DMS',
    'author': 'Soy Calidad',
    'website': 'www.soycalidad.com',
    'license': '',
    'category': 'dms',
    'depends': [
        'mgmtsystem_audit',
        'mgmtsystem_employees',
        'mgmtsystem_process',
        'mgmtsystem_context',
        'mgmtsystem_comunication',
        'mgmtsystem_legal',
        'mgmtsystem_survey',
        'mgmtsystem_management_review',
        'mgmtsystem_infrastructure',
        'mgmtsystem_nonconformity',
        'mgmtsystem_action',
        'soycalidad_improve',
    ],
    'data': [
        'data/dms.xml',
        'views/dms.xml',
        'views/employees.xml',
        'views/process.xml',
        'views/context.xml',
        'views/opportunity.xml',
        'views/comunication.xml',
        'views/legal.xml',
        'views/survey.xml',
        'views/target.xml',
        'views/maintenance.xml',
        'views/management_review.xml',
        'views/nc.xml',
        'views/action.xml',
        'views/partner.xml',
        'views/audit.xml',
        'views/improve.xml',
    ],
    'auto_install': False,
    'application': False,
}