{
  'name': 'Cargar data para el modulo : Auditoría TYT Contact Center - Soy Calidad',
    'version': '1.0',
    'description': 'Añade registros al módulo Auditoría TYT Contact Center',
    'summary': 'Añade registros al módulo Auditoría TYT Contact Center',
    'author': 'Soy Calidad',
    'website': 'www.soycalidad.com',
    'license': 'Other proprietary',
    'category': 'soycalidad',
    'depends': [
        'tyt_audit',
    ],
    'data': [
        'data/clauses_calidad.xml',
        'data/clauses_op.xml',
        'data/clauses_hr.xml',
        'data/clauses_ri.xml',
        'data/clauses_sys.xml',
        'data/audit_audit_planning_ca.xml',
        'data/audit_audit_planning_op.xml',
        'data/audit_audit_planning_hr.xml',
        'data/audit_audit_planning_ri.xml',
        'data/audit_audit_planning_sys.xml',
        'data/audit_audit_planning_add.xml',
    ],
    'auto_install': False,
    'installable': True,
    'application': False,
}